
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from '@/app/navbar/page'
import Footer from "./footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IXth-Science",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="lofi">   
      <body className={inter.className}>
        <Toaster/>
        <Navbar></Navbar>
         <div className='mt-20'>{children}</div> 
        <Footer/>
      </body>
    </html>
  );
}
