
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from '@/app/navbar/page'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="lofi">
      <body className={inter.className}>
        <Toaster/>
        <Navbar></Navbar>
       <div className='mt-20'>{children}</div> 

      </body>
    </html>
  );
}
